src/java/it/univr/musiclovers/model/beans/CustomerBean.java
package it.univr.musiclovers.model.beans;

import java.io.Serializable;

/**
 *
 * @author blasco991
 */
public class CustomerBean implements Serializable {

    private int ID;
    private String city;
    private String code;
    private String email;
    private String mobile;
    private String name;
    private String surname;
    private String telephone;
    private static final long serialVersionUID = 1L;

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public int getID() {
        return ID;
    }

    public void setID(int ID) {
        this.ID = ID;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getTelephone() {
        return telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

}

src/java/it/univr/musiclovers/model/beans/ProductBean.java
package it.univr.musiclovers.model.beans;

import it.univr.musiclovers.model.Model;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class ProductBean implements Serializable {

    private int ID;

    private BrandBean brand = new BrandBean();
    private String description;
    private boolean forChild;
    private boolean inexpensive;
    private String insertDate = Model.today();
    private int minAge;
    private String name;
    private boolean online;
    private float price;
    private List<String> productImage = new ArrayList<>();
    private boolean professional;
    private ProfessionalBean owner = new ProfessionalBean();
    private boolean status;
    private boolean used;
    private float weight;

    private static final long serialVersionUID = 1L;

    public BrandBean getBrand() {
        return brand;
    }

    public void setBrand(BrandBean brand) {
        this.brand = brand;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getID() {
        return ID;
    }

    public void setID(int ID) {
        this.ID = ID;
    }

    public String getInsertDate() {
        return insertDate;
    }

    public void setInsertDate(String insertDate) {
        this.insertDate = insertDate;
    }

    public int getMinAge() {
        return minAge;
    }

    public void setMinAge(int min_age) {
        this.minAge = min_age;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public float getPrice() {
        return price;
    }

    public void setPrice(float price) {
        this.price = price;
    }

    public void setProductImage(List<String> product_image) {
        this.productImage = new ArrayList<>(product_image);
    }

    public List<String> getProductImages() {
        return productImage;
    }

    public ProfessionalBean getOwner() {
        return owner;
    }

    public void setOwner(ProfessionalBean owner) {
        this.owner = owner;
    }

    public String getThumb() {
        if (productImage.isEmpty()) {
            return "img/image-not-found.png";
        } else {
            return productImage.get(0);
        }
    }

    public float getWeight() {
        return weight;
    }

    public void setWeight(float weight) {
        this.weight = weight;
    }

    public boolean isForChild() {
        return forChild;
    }

    public void setForChild(boolean forChild) {
        this.forChild = forChild;
    }

    public boolean isInexpensive() {
        return inexpensive;
    }

    public void setInexpensive(boolean inexpensive) {
        this.inexpensive = inexpensive;
    }

    public boolean isOnline() {
        return online;
    }

    public void setOnline(boolean online) {
        this.online = online;
    }

    public boolean isProfessional() {
        return professional;
    }

    public void setProfessional(boolean professional) {
        this.professional = professional;
    }

    public boolean isStatus() {
        return status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

    public boolean isUsed() {
        return used;
    }

    public void setUsed(boolean used) {
        this.used = used;
    }

}

src/java/it/univr/musiclovers/controller/AuthenticationController.java
package it.univr.musiclovers.controller;

import it.univr.musiclovers.model.CustomerModel;
import it.univr.musiclovers.model.EmployerModel;
import it.univr.musiclovers.model.beans.AccountBean;
import it.univr.musiclovers.model.beans.CustomerBean;
import it.univr.musiclovers.model.beans.PersonBean;
import java.io.IOException;
import java.sql.SQLException;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

/**
 *
 * @author blasco991
 */
@ManagedBean
@SessionScoped
public class AuthenticationController extends ControllerModel {

    private AccountBean accountBean = new AccountBean();
    private boolean logged = false;
    private static final long serialVersionUID = 1L;

    public void check() throws IOException {
        if (isLogged() && accountBean.isEmployer()) {
            redirect("employer/");
        } else if (isLogged() && accountBean.isProfessional()) {
            redirect("customer/");
        }
    }

    public void checkEmployer() throws IOException {
        if (!isLogged() || !accountBean.isEmployer()) {
            redirect("login");
        }
    }

    public void checkProfessional() throws IOException {
        if (!isLogged() || !accountBean.isProfessional()) {
            redirect("login");
        }
    }

    public String getPassword() {
        return accountBean.getPassword();
    }

    public void setPassword(String password) {
        accountBean.setPassword(password);
    }

    public int getProfessionalID() {
        return ((CustomerBean) accountBean.getPerson()).getID();
    }

    public String getUsername() {
        return accountBean.getUsername();
    }

    public void setUsername(String username) {
        accountBean.setUsername(username);
    }

    public boolean isLogged() {
        return logged;
    }

    public String login(String componendID, AccountBean account, String outcome) {
        if (account != null && account.getPerson() != null) {
            accountBean = account;
            logged = true;
            return redirectString(outcome);
        } else {
            FacesContext.getCurrentInstance().addMessage(componendID, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Username o Password errati!", "Username o Password errati!"));
            return addExt("login");
        }
    }

    public String loginEmployer() throws SQLException {
        AccountBean account = EmployerModel.getAccount(accountBean.getUsername(), accountBean.getPassword());
        return login("loginEmployer", account, "employer/");
    }

    public String loginProfessional() throws SQLException {
        AccountBean account = CustomerModel.getAccount(accountBean.getUsername(), accountBean.getPassword());
        return login("loginProfessional", account, "customer/");
    }

    public String logout() {
        accountBean = new AccountBean();
        logged = false;
        return redirectString("/homepage");
    }

}

src/java/it/univr/musiclovers/controller/CustomerController.java
package it.univr.musiclovers.controller;

import it.univr.musiclovers.model.CustomerModel;
import it.univr.musiclovers.model.OrderModel;
import it.univr.musiclovers.model.ProductModel;
import it.univr.musiclovers.model.beans.AccountBean;
import it.univr.musiclovers.model.beans.CustomerBean;
import it.univr.musiclovers.model.beans.ProfessionalBean;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

/**
 *
 * @author Luca Zidda
 */
@ManagedBean
@SessionScoped
public class CustomerController extends ControllerModel {

    private AccountBean accountBean;
    private boolean isProfessional;
    private ProfessionalBean professionalBean;
    private CustomerBean selectedCustomer;
    private static final long serialVersionUID = 1L;

    public AccountBean getAccountBean() {
        return accountBean;
    }

    public String getCustomer(int customerID) {
        return addParam(normalizeUrl("customer"), "customerID", String.valueOf(customerID));
    }

    public List<CustomerBean> getCustomers() throws SQLException {
        return CustomerModel.getCustomers();
    }

    public ProfessionalBean getProfessionalBean() {
        return professionalBean;
    }

    public List<Integer> getProfessionalIDs() throws SQLException {
        return CustomerModel.getProfessionalIDs();
    }

    public List<ProfessionalBean> getProfessionals() throws SQLException {
        return CustomerModel.getProfessionals();
    }

    public CustomerBean getSelectedCustomer() {
        return selectedCustomer;
    }

    public void setSelectedCustomer(int customerID) throws SQLException {
        this.selectedCustomer = CustomerModel.getCustomer(customerID);
        this.accountBean = CustomerModel.getAccount(CustomerModel.getProfessional(customerID).getAccountID());
        this.professionalBean = (ProfessionalBean) accountBean.getPerson();
    }

    public boolean isIsProfessional() {
        return isProfessional;
    }

    public void setIsProfessional(boolean isProfessional) {
        this.isProfessional = isProfessional;
    }

    public String processCustomerForm() throws SQLException {
        if (selectedCustomer != null && professionalBean != null) {
            if (selectedCustomer.getID() > 0) {
                CustomerModel.editCustomer(selectedCustomer);
                if (isIsProfessional() && accountBean != null) {
                    if (((CustomerBean) accountBean.getPerson()).getID() > 0) {
                        CustomerModel.editProfessional(accountBean);
                    } else {
                        CustomerModel.insertProfessional(accountBean);
                    }
                }
            } else {
                CustomerModel.insertCustomer(selectedCustomer);
                if (isIsProfessional()) {
                    ProfessionalBean pb = new ProfessionalBean(selectedCustomer, this.professionalBean.getRole(), this.professionalBean.getReduction());
                    accountBean.setPerson(pb);
                    CustomerModel.insertProfessional(accountBean);
                }
            }
        }
        return redirectString("index.xhtml");
    }

    public void removeCustomer(int customerID) throws SQLException, ParseException {
        if (OrderModel.getOrdersByCustomer(customerID).isEmpty() && ProductModel.getProductsByOwner(customerID).isEmpty()) {
            CustomerModel.removeCustomer(customerID);
        } else {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Errore", ":  impossibile eliminare un cliente a cui vi sono ancora ordini associati!"));
        }
    }

}

web/customer/index.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <head><title>IGNORED</title></head>
    <body>
        <ui:composition template="/templates/template.jsf">
            <f:metadata>
                <f:event type="preRenderView" listener="${authenticationController.checkProfessional()}"/>
            </f:metadata>
            <ui:define name="windowTitle">Administration</ui:define>
            <ui:define name="content">
                <div class="page-header">
                    <h1>Bentornato <small>| ${authenticationController.username}!</small></h1>
                </div>
                <div class="row">
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active">
                            <a href="#selling" aria-controls="home" role="tab" data-toggle="tab">Vendite</a>
                        </li>
                        <li role="presentation">
                            <a href="#bid" aria-controls="home" role="tab" data-toggle="tab">Acquisti</a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane active fade in table-responsive" id="selling" >
                            <h:dataTable value="${orderController.getOrdersBySeller(authenticationController.professionalID)}" var="order" 
                                         styleClass="table table-bordered table-hover table-responsive" 
                                         headerClass="text-center" rowClasses="text-center" 
                                         columnClasses="column-image,,,,column-date,,,,vertical-middle">
                                <h:column>    				
                                    <f:facet name="header">Product</f:facet>    
                                    <div class="gallery">
                                        <a href="${order.product.thumb}" data-source="${order.product.thumb}" title="${order.product.name}">
                                            <img class="img-responsive img-thumbnail" src="${order.product.thumb}" />
                                        </a>
                                    </div>
                                    <b><h:link value="${order.product.name}" outcome="${productController.getProductInfo(order.product.ID)}" target="_blank"/></b>
                                </h:column>                      
                                <h:column>    				
                                    <f:facet name="header"># ID</f:facet>${order.ID}</h:column>                      
                                <h:column><f:facet name="header">Price</f:facet>${order.price}</h:column>                      
                                <h:column><f:facet name="header">Payment Type</f:facet>${order.paymentType}</h:column>                      
                                <h:column><f:facet name="header">Sold date</f:facet>${order.soldDate}</h:column>                      
                                <h:column><f:facet name="header">Employer</f:facet>${order.seller.code}</h:column>
                                <h:column><f:facet name="header">Data inserzione</f:facet>${order.product.insertDate}</h:column>                      
                            </h:dataTable>
                        </div>
                        <div role="tabpanel" class="tab-pane fade table-responsive" id="bid" >
                            <h:dataTable value="${orderController.getOrdersByBuyer(authenticationController.professionalID)}" var="order" 
                                         styleClass="table table-bordered table-hover table-responsive" 
                                         headerClass="text-center" rowClasses="text-center" 
                                         columnClasses="column-image,,,,column-date,,,,vertical-middle">
                                <h:column>    				
                                    <f:facet name="header">Product</f:facet>    
                                    <div class="gallery">
                                        <a href="${order.product.thumb}" data-source="${order.product.thumb}" title="${order.product.name}">
                                            <img class="img-responsive img-thumbnail" src="${order.product.thumb}" />
                                        </a>
                                    </div>
                                    <b><h:link value="${order.product.name}" outcome="${productController.getProductInfo(order.product.ID)}" target="_blank"/></b>
                                </h:column>                      
                                <h:column><f:facet name="header"># ID</f:facet>${order.ID}</h:column>                      
                                <h:column><f:facet name="header">Price</f:facet>${order.price}</h:column>                      
                                <h:column><f:facet name="header">Payment Type</f:facet>${order.paymentType}</h:column>                      
                                <h:column><f:facet name="header">Sold date</f:facet>${order.soldDate}</h:column>                      
                                <h:column><f:facet name="header">Employer</f:facet>${order.seller.code}</h:column>                      
                                <h:column><f:facet name="header">Owner</f:facet>${order.product.owner.email}</h:column>                      
                            </h:dataTable>
                        </div>                        
                    </div> 
                </div> 
            </ui:define>
        </ui:composition>
    </body>
</html>