src/java/it/univr/musiclovers/model/beans/ProductBean.java
package it.univr.musiclovers.model.beans;

import it.univr.musiclovers.model.Model;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class ProductBean implements Serializable {

    private int ID;

    private BrandBean brand = new BrandBean();
    private String description;
    private boolean forChild;
    private boolean inexpensive;
    private String insertDate = Model.today();
    private int minAge;
    private String name;
    private boolean online;
    private float price;
    private List<String> productImage = new ArrayList<>();
    private boolean professional;
    private ProfessionalBean owner = new ProfessionalBean();
    private boolean status;
    private boolean used;
    private float weight;

    private static final long serialVersionUID = 1L;

    public BrandBean getBrand() {
        return brand;
    }

    public void setBrand(BrandBean brand) {
        this.brand = brand;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getID() {
        return ID;
    }

    public void setID(int ID) {
        this.ID = ID;
    }

    public String getInsertDate() {
        return insertDate;
    }

    public void setInsertDate(String insertDate) {
        this.insertDate = insertDate;
    }

    public int getMinAge() {
        return minAge;
    }

    public void setMinAge(int min_age) {
        this.minAge = min_age;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public float getPrice() {
        return price;
    }

    public void setPrice(float price) {
        this.price = price;
    }

    public void setProductImage(List<String> product_image) {
        this.productImage = new ArrayList<>(product_image);
    }

    public List<String> getProductImages() {
        return productImage;
    }

    public ProfessionalBean getOwner() {
        return owner;
    }

    public void setOwner(ProfessionalBean owner) {
        this.owner = owner;
    }

    public String getThumb() {
        if (productImage.isEmpty()) {
            return "img/image-not-found.png";
        } else {
            return productImage.get(0);
        }
    }

    public float getWeight() {
        return weight;
    }

    public void setWeight(float weight) {
        this.weight = weight;
    }

    public boolean isForChild() {
        return forChild;
    }

    public void setForChild(boolean forChild) {
        this.forChild = forChild;
    }

    public boolean isInexpensive() {
        return inexpensive;
    }

    public void setInexpensive(boolean inexpensive) {
        this.inexpensive = inexpensive;
    }

    public boolean isOnline() {
        return online;
    }

    public void setOnline(boolean online) {
        this.online = online;
    }

    public boolean isProfessional() {
        return professional;
    }

    public void setProfessional(boolean professional) {
        this.professional = professional;
    }

    public boolean isStatus() {
        return status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

    public boolean isUsed() {
        return used;
    }

    public void setUsed(boolean used) {
        this.used = used;
    }

}

src/java/it/univr/musiclovers/controller/BrandController.java
package it.univr.musiclovers.controller;

import it.univr.musiclovers.model.BrandModel;
import it.univr.musiclovers.model.ProductModel;
import it.univr.musiclovers.model.beans.BrandBean;
import it.univr.musiclovers.model.beans.ProductBean;
import java.io.*;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.ServletContext;
import javax.servlet.http.Part;

/**
 *
 * @author Marian Solomon
 */
@ManagedBean
@SessionScoped
public class BrandController extends ControllerModel {

    private transient Part file;
    private BrandBean selectedBrand;
    private static final long serialVersionUID = 1L;

    public String getBrand(int brandID) {
        return addParam(normalizeUrl("brand"), "brandID", String.valueOf(brandID));
    }

    public String getBrandInfo(int brandID) {
        return addParam(normalizeUrl("/brand"), "brandID", String.valueOf(brandID));
    }

    public List<BrandBean> getBrands() throws SQLException {
        return BrandModel.getBrands();
    }

    public Part getFile() {
        return file;
    }

    public void setFile(Part file) {
        this.file = file;
    }

    public List<ProductBean> getProducts() throws SQLException {
        return ProductModel.getProductsByBrand(selectedBrand.getID());
    }

    public BrandBean getSelectedBrand() {
        return selectedBrand;
    }

    public void setSelectedBrand(int brandId) throws SQLException {
        this.selectedBrand = BrandModel.getBrand(brandId);
    }

    public String processBrandForm() throws SQLException {
        if (selectedBrand.getID() > 0) {
            BrandModel.editBrand(selectedBrand);
        } else {
            BrandModel.insertBrand(selectedBrand);
        }
        return "index.xhtml";
    }

    public void processImage() {
        if (file != null) {
            try (InputStream inputStream = file.getInputStream()) {
                String pathWebBuild = ((ServletContext) FacesContext.getCurrentInstance().getExternalContext().getContext()).getRealPath("");
                String pathWebSrc = pathWebBuild + "/img/brands/";
                File outputFile = new File(pathWebSrc + File.separator + File.separator + getFilename(file));
                try (FileOutputStream outputStream = new FileOutputStream(outputFile)) {
                    byte[] buffer = new byte[4096];
                    int bytesRead = 0;
                    while (true) {
                        bytesRead = inputStream.read(buffer);
                        if (bytesRead > 0) {
                            outputStream.write(buffer, 0, bytesRead);
                        } else {
                            break;
                        }
                    }
                }
                selectedBrand.setLogo("img/brands/" + getFilename(file));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(ProductController.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(ProductController.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void removeBrand(int brandID) throws SQLException, ParseException {
        if (BrandModel.getBrandsByProduct(brandID).isEmpty()) {
            BrandModel.removeBrand(brandID);
        } else {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Errore", ":  impossibile eliminare un brand a cui vi sono ancora prodotti associati!"));
        }
    }

    public void removeLogo(String logo) throws SQLException {
        selectedBrand.setLogo("img/image-not-found.png");
    }

    private static String getFilename(Part part) {
        for (String cd : part.getHeader("content-disposition").split(";")) {
            if (cd.trim().startsWith("filename")) {
                String filename = cd.substring(cd.indexOf('=') + 1).trim().replace("\"", "");
                return filename.substring(filename.lastIndexOf('/') + 1).substring(filename.lastIndexOf('\\') + 1); // MSIE fix.
            }
        }
        return null;
    }

}

src/java/it/univr/musiclovers/controller/CustomerController.java
package it.univr.musiclovers.controller;

import it.univr.musiclovers.model.CustomerModel;
import it.univr.musiclovers.model.OrderModel;
import it.univr.musiclovers.model.ProductModel;
import it.univr.musiclovers.model.beans.AccountBean;
import it.univr.musiclovers.model.beans.CustomerBean;
import it.univr.musiclovers.model.beans.ProfessionalBean;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

/**
 *
 * @author Luca Zidda
 */
@ManagedBean
@SessionScoped
public class CustomerController extends ControllerModel {

    private AccountBean accountBean;
    private boolean isProfessional;
    private ProfessionalBean professionalBean;
    private CustomerBean selectedCustomer;
    private static final long serialVersionUID = 1L;

    public AccountBean getAccountBean() {
        return accountBean;
    }

    public String getCustomer(int customerID) {
        return addParam(normalizeUrl("customer"), "customerID", String.valueOf(customerID));
    }

    public List<CustomerBean> getCustomers() throws SQLException {
        return CustomerModel.getCustomers();
    }

    public ProfessionalBean getProfessionalBean() {
        return professionalBean;
    }

    public List<Integer> getProfessionalIDs() throws SQLException {
        return CustomerModel.getProfessionalIDs();
    }

    public List<ProfessionalBean> getProfessionals() throws SQLException {
        return CustomerModel.getProfessionals();
    }

    public CustomerBean getSelectedCustomer() {
        return selectedCustomer;
    }

    public void setSelectedCustomer(int customerID) throws SQLException {
        this.selectedCustomer = CustomerModel.getCustomer(customerID);
        this.accountBean = CustomerModel.getAccount(CustomerModel.getProfessional(customerID).getAccountID());
        this.professionalBean = (ProfessionalBean) accountBean.getPerson();
    }

    public boolean isIsProfessional() {
        return isProfessional;
    }

    public void setIsProfessional(boolean isProfessional) {
        this.isProfessional = isProfessional;
    }

    public String processCustomerForm() throws SQLException {
        if (selectedCustomer != null && professionalBean != null) {
            if (selectedCustomer.getID() > 0) {
                CustomerModel.editCustomer(selectedCustomer);
                if (isIsProfessional() && accountBean != null) {
                    if (((CustomerBean) accountBean.getPerson()).getID() > 0) {
                        CustomerModel.editProfessional(accountBean);
                    } else {
                        CustomerModel.insertProfessional(accountBean);
                    }
                }
            } else {
                CustomerModel.insertCustomer(selectedCustomer);
                if (isIsProfessional()) {
                    ProfessionalBean pb = new ProfessionalBean(selectedCustomer, this.professionalBean.getRole(), this.professionalBean.getReduction());
                    accountBean.setPerson(pb);
                    CustomerModel.insertProfessional(accountBean);
                }
            }
        }
        return redirectString("index.xhtml");
    }

    public void removeCustomer(int customerID) throws SQLException, ParseException {
        if (OrderModel.getOrdersByCustomer(customerID).isEmpty() && ProductModel.getProductsByOwner(customerID).isEmpty()) {
            CustomerModel.removeCustomer(customerID);
        } else {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Errore", ":  impossibile eliminare un cliente a cui vi sono ancora ordini associati!"));
        }
    }

}

src/java/it/univr/musiclovers/controller/EmployerController.java
package it.univr.musiclovers.controller;

import it.univr.musiclovers.model.CustomerModel;
import it.univr.musiclovers.model.EmployerModel;
import it.univr.musiclovers.model.OrderModel;
import it.univr.musiclovers.model.ProductModel;
import it.univr.musiclovers.model.beans.AccountBean;
import it.univr.musiclovers.model.beans.EmployerBean;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

/**
 *
 * @author Luca Zidda
 */
@ManagedBean
@SessionScoped
public class EmployerController extends ControllerModel {

    private AccountBean selectedAccount;
    private static final long serialVersionUID = 1L;

    public String getEmployer(int employerID) {
        return addParam(normalizeUrl("employer"), "employerID", String.valueOf(employerID));
    }

    public EmployerBean getEmployer() {
        return (EmployerBean) selectedAccount.getPerson();
    }

    public List<EmployerBean> getEmployers() throws SQLException {
        return EmployerModel.getEmployers();
    }

    public AccountBean getSelectedAccount() {
        return selectedAccount;
    }

    public void setSelectedEmployer(int employerID) throws SQLException {
        this.selectedAccount = EmployerModel.getAccountByEmployer(employerID);
    }

    public String processCustomerForm() throws SQLException {
        if (selectedAccount.getID() > 0) {
            EmployerModel.editEmployer(selectedAccount);
        } else {
            EmployerModel.insertEmployer(selectedAccount);
        }
        return redirectString("index.xhtml");
    }

    public void removeEmployer(int employerID) throws SQLException, ParseException {
        if (OrderModel.getOrdersBySeller(employerID).isEmpty()) {
            EmployerModel.removeEmployer(employerID);
        } else {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Errore", ":  impossibile eliminare un dipendente a cui vi sono ancora ordini associati!"));
        }
    }

}

src/java/it/univr/musiclovers/controller/OrderController.java
package it.univr.musiclovers.controller;

import static it.univr.musiclovers.controller.ControllerModel.redirectString;
import it.univr.musiclovers.model.CustomerModel;
import it.univr.musiclovers.model.OrderModel;
import it.univr.musiclovers.model.ProductModel;
import it.univr.musiclovers.model.beans.EmployerBean;
import it.univr.musiclovers.model.beans.OrderBean;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 *
 * @author Marian Solomon
 */
@ManagedBean
@SessionScoped
public class OrderController extends ControllerModel {

    private float original;
    private int reduction;
    private OrderBean selectedOrder;
    private static final long serialVersionUID = 1L;

    public List<EmployerBean> getEmployers() throws SQLException {
        return OrderModel.getEmployers();
    }

    public String getOrder(int orderID) {
        return addParam(normalizeUrl("order"), "orderID", String.valueOf(orderID));
    }

    public List<OrderBean> getOrders() throws SQLException, ParseException {
        return OrderModel.getOrders();
    }

    public List<OrderBean> getOrdersByBuyer(int buyerID) throws SQLException, ParseException {
        return OrderModel.getOrdersByBuyer(buyerID);
    }

    public List<OrderBean> getOrdersBySeller(int sellerID) throws SQLException, ParseException {
        return OrderModel.getOrdersBySeller(sellerID);
    }

    public void setPrice(int productID) throws SQLException {
        selectedOrder.setPrice(ProductModel.getProduct(productID).getPrice());
        original = selectedOrder.getPrice();
        updatePrice();
    }

    public int getReduction() {
        return reduction;
    }

    public void setReduction(int customerID) throws SQLException {
        if (CustomerModel.isProfessional(customerID)) {
            reduction = CustomerModel.getProfessional(customerID).getReduction();
        } else {
            reduction = 0;
        }
        updatePrice();
    }

    public OrderBean getSelectedOrder() {
        return selectedOrder;
    }

    public void setSelectedOrder(int orderID) throws SQLException, ParseException {
        this.selectedOrder = OrderModel.getOrder(orderID);
    }

    public String processOrderForm() throws SQLException {
        if (selectedOrder != null) {
            if (selectedOrder.getID() > 0) {
                OrderModel.editOrder(selectedOrder);
            } else {
                OrderModel.insertOrder(selectedOrder);
            }
        }
        return redirectString("index.xhtml");
    }

    public void removeOrder(int orderID) throws SQLException {
        OrderModel.removeOrder(orderID);
    }

    private void updatePrice() {
        selectedOrder.setPrice(original - original / 100 * reduction);
    }

}

web/employer/brand.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <head>
        <link rel="stylesheet" href="../css/bootstrap.css" />
        <link rel="stylesheet" href="../css/bootstrap-theme.css" />
        <link rel="stylesheet" href="../css/custom.css" />
        <title>IGNORED</title>
    </head>
    <body>
        <ui:composition template="/templates/template.jsf">
            <f:metadata>
                <f:event type="preRenderView" listener="${authenticationController.checkEmployer()}" />
                <f:viewAction action="${brandController.setSelectedBrand(param.brandID)}"/>
            </f:metadata>
            <ui:define name="windowTitle">Brand</ui:define>
            <ui:define name="content">
                <div class="page-header">
                    <p class="lead">
                        <h:outputText value="Modifica brand" rendered="${brandController.selectedBrand.ID > 0}"/>
                        <h:outputText value="Inserisci brand" rendered="${brandController.selectedBrand.ID == 0}"/>
                    </p>
                </div>
                <h:form id="brand-form" class="form-horizontal">
                    <div class="form-group">
                        <h:button outcome="${brandController.cancel()}" value="Annulla" class="btn btn-danger col-md-2 col-xs-4 col-md-offset-2 col-xs-offset-1"/>
                        <h:commandButton action="${brandController.processBrandForm()}" value="Invia" type="submit" class="btn btn-success col-md-2 col-xs-4 col-md-offset-1 col-xs-offset-1"/>
                    </div>
                    <div class="form-group">
                        <h:outputLabel value="ID :" class="col-xs-2 control-label"/>
                        <div class="col-xs-1">
                            <h:inputText value="${brandController.selectedBrand.ID}" disabled="true" class="form-control"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <h:outputLabel value="Nome :" for="brandName" class="col-xs-2 control-label"/>
                        <div class="col-xs-5">
                            <h:inputText value="${brandController.selectedBrand.name}" id="brandName" class="form-control" required="true" requiredMessage="Il nome è obbligatorio" validatorMessage="Il nome non è valido, per favore inserire un nome da 1 a 64 caratteri, senza doppi apici e caratteri speciali al di fuori di questi: @#_+.()\'-">
                                <f:validateRegex pattern="([a-zA-Z0-9.()\s-èòàùì'é@#_+]){1,63}" />
                                <f:validateLength minimum="1" />
                                <f:validateLength maximum="63" /> 
                            </h:inputText>
                        </div>
                        <h:message for="brandName" styleClass="alert alert-danger col-xs-5" />
                    </div>
                    <div class="form-group">
                        <h:outputLabel value="Sito web :" for="brandLink" class="col-xs-2 control-label"/>
                        <div class="col-xs-5">
                            <h:inputText value="${brandController.selectedBrand.link}" id="brandLink" class="form-control" validatorMessage="L'url inserito non è valido, per favore inserirne uno valido e non maggiore di 255 caratteri">
                                <f:validateRegex pattern="^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$" />
                                <f:validateLength minimum="1" />
                                <f:validateLength maximum="255" />
                            </h:inputText>   
                        </div>  
                        <h:message for="brandLink" styleClass="alert alert-danger col-xs-5" />
                    </div>                    
                    <div class="form-group">
                        <h:outputLabel value="Descrizione :" for="brandDescription" class="col-xs-2 control-label"/>
                        <div class="col-xs-5">
                            <h:inputTextarea value="${brandController.selectedBrand.description}" id="brandDescription" class="form-control" rows="5"/>
                        </div>
                    </div>                                                            
                </h:form>
                <h:panelGroup layout="block" id="image-list" class="form-group col-lg-12 col-md-12 col-sm-12 col-xs-12 margin-10">
                    <div class="col-xs-1"></div>
                    <h:outputLabel value="Logo :" class="col-xs-1 control-label"/>
                    <div class="col-xs-4">
                        <h:graphicImage value="${brandController.selectedBrand.logo}" class="little-thumb" id="brand-logo"/>
                    </div>
                    <div class="col-xs-1">
                        <f:ajax event="valueChange" listener="${brandController.processImage()}" execute="logo" render="brand-logo">
                            <h:form enctype="multipart/form-data">
                                <h:inputFile id="logo" value="${brandController.file}"/>
                            </h:form>
                        </f:ajax>
                    </div>
                </h:panelGroup>
            </ui:define>
        </ui:composition>
    </body>
</html>

web/employer/order.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough">
    <head>
        <link rel="stylesheet" href="../css/bootstrap.css" />
        <link rel="stylesheet" href="../css/bootstrap-theme.css" />
        <link rel="stylesheet" href="../css/custom.css" />
        <title>IGNORED</title>
    </head>
    <body>
        <ui:composition template="/templates/template.jsf">
            <f:metadata>
                <f:event type="preRenderView" listener="${authenticationController.checkEmployer()}" />
                <f:viewAction action="${orderController.setSelectedOrder(param.orderID)}"/>
            </f:metadata>
            <ui:define name="windowTitle">Order</ui:define>
            <ui:define name="content">
                <div class="page-header">
                    <p class="lead">
                        <h:outputText value="Modifica order" rendered="${orderController.selectedOrder.ID > 0}"/>
                        <h:outputText value="Inserisci order" rendered="${orderController.selectedOrder.ID == 0}"/>
                    </p>
                </div>
                <h:form id="order-form" class="form-horizontal col-xs-12">
                    <div class="form-group">
                        <h:outputLabel value="ID :" class="col-xs-2 control-label"/>
                        <div class="col-xs-1">
                            <h:inputText value="${orderController.selectedOrder.ID}" disabled="true" class="form-control"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <h:outputLabel value="Prodotto :" for="orderProduct" class="col-xs-2 control-label"/>
                        <div class="col-xs-5">
                            <h:selectOneMenu value="${orderController.selectedOrder.product.ID}" id="orderProduct" styleClass="form-control height-34" required="true" requiredMessage="Il prodotto è obbligatorio">
                                <f:selectItem itemDisabled="true" itemValue="0" itemLabel="Seleziona il prodotto" />
                                <f:selectItems value="${productController.products}" var="product" itemLabel="${product.name}" itemValue="${product.ID}" />
                                <f:ajax event="change" listener="${orderController.setPrice(orderController.selectedOrder.product.ID)}" render="orderPrice" execute="orderProduct"/>
                            </h:selectOneMenu>
                        </div>
                        <h:message for="orderProduct" styleClass="alert alert-danger col-xs-5" />
                    </div>
                    <div class="form-group">
                        <h:outputLabel value="Prezzo :" for="orderPrice" class="col-xs-2 control-label"/>
                        <div class="col-xs-2">
                            <h:inputText value="${orderController.selectedOrder.price}" id="orderPrice" class="form-control" required="true" requiredMessage="Il prezzo è obbligatorio" validatorMessage="Il prezzo non è valido, per favore inserire un prezzo tra 0.01 e 1000000000">
                                <f:convertNumber type="currency" pattern="#0.00" />
                                <f:validateDoubleRange minimum="0.01" maximum="1000000000" />
                            </h:inputText>
                        </div>
                        <h:message for="orderPrice" styleClass="alert alert-danger col-xs-5" />                        
                    </div>
                    <div class="form-group">
                        <h:outputLabel value="Pagamento :" for="orderPaymentType" class="col-xs-2 control-label"/>
                        <div class="col-xs-5">
                            <h:inputText value="${orderController.selectedOrder.paymentType}" id="orderPaymentType" class="form-control" required="true" requiredMessage="La modalità di pagamento è obbligatoria" validatorMessage="La modalità di pagamento non è valida, per favore non inserire caratteri particolari, e stringhe oltre i 45 caratteri" >
                                <f:validateRegex pattern="[a-zA-Z0-9. ()s-èòàùì'é_+]{1,20}" />
                                <f:validateLength minimum="1" />
                                <f:validateLength maximum="45" />
                            </h:inputText>
                        </div>
                        <h:message for="orderPaymentType" styleClass="alert alert-danger col-xs-5" />                        
                    </div>
                    <div class="form-group">
                        <h:outputLabel value="Acquirente :" for="orderBuyer" class="col-xs-2 control-label"/>
                        <div class="col-xs-5">
                            <h:selectOneMenu value="${orderController.selectedOrder.buyer.ID}" id="orderBuyer" styleClass="form-control height-34" required="true" requiredMessage="L'acquirente è obbligatorio">
                                <f:selectItem itemDisabled="true" itemValue="0" itemLabel="Seleziona l'acquirente" />
                                <f:selectItems value="${customerController.customers}" var="customer" itemLabel="${customer.email}" itemValue="${customer.ID}" />
                                <f:ajax event="change" listener="${orderController.setReduction(orderController.selectedOrder.buyer.ID)}" render="orderPrice" execute="orderProduct"/>
                            </h:selectOneMenu>
                        </div>
                        <h:message for="orderBuyer" styleClass="alert alert-danger col-xs-5" />
                    </div>
                    <div class="form-group">
                        <h:outputLabel value="Commesso :" for="orderSeller" class="col-xs-2 control-label"/>
                        <div class="col-xs-5">
                            <h:selectOneMenu value="${orderController.selectedOrder.seller.ID}" id="orderSeller" styleClass="form-control height-34" required="true" requiredMessage="Il commesso è obbligatorio">
                                <f:selectItem itemDisabled="true" itemValue="0" itemLabel="Seleziona il commesso" />
                                <f:selectItems value="${orderController.employers}" var="employer" itemLabel="${employer.ID}: ${employer.name} ${employer.surname}" itemValue="${employer.ID}" />
                            </h:selectOneMenu>
                        </div>
                        <h:message for="orderSeller" styleClass="alert alert-danger col-xs-5" />
                    </div>
                    <div class="form-group">
                        <h:outputLabel value="Data di vendita :" for="orderSoldDate" class="col-xs-2 control-label"/>
                        <div class="col-xs-5">
                            <h:inputText disabled="true" value="${orderController.selectedOrder.soldDate}" id="orderSoldDate" class="form-control"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <h:button outcome="${orderController.cancel()}" value="Annulla" class="btn btn-danger col-md-2 col-xs-4 col-xs-offset-1"/>
                        <h:commandButton action="${orderController.processOrderForm()}" value="Invia" type="submit" class="btn btn-success col-md-offset-3 col-xs-offset-1 col-md-2 col-xs-4"/>
                    </div>
                </h:form>                
            </ui:define>
        </ui:composition>
    </body>
</html>