src/java/it/univr/musiclovers/model/ProductModel.java
package it.univr.musiclovers.model;

import it.univr.musiclovers.model.beans.ProductBean;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.*;
import java.util.Map.Entry;

/**
 *
 * @author Marian Solomon
 */
public abstract class ProductModel extends Model {

    private static final String queryEditProduct = "UPDATE " + getTablePrefix() + "_product SET status = ?, online = ?, weight = ?, price = ?, name = ?, description = ?, inexpensive = ?, professional = ?, for_child = ?, used = ?, min_age = ?, brand_id = ? WHERE id = ?";
    private static final String queryGetOnlineProducts = "SELECT * FROM " + getTablePrefix() + "_PRODUCT WHERE online = 'true'";
    private static final String queryGetProduct = "SELECT * FROM " + getTablePrefix() + "_PRODUCT WHERE id = ?";
    private static final String queryGetProductImages = "SELECT image FROM " + getTablePrefix() + "_product_images WHERE product_id = ?";
    private static final String queryGetProductsByBrand = "SELECT * FROM " + getTablePrefix() + "_product WHERE brand_id = ? ORDER BY id ASC";
    private static final String queryGetProductsByOwner = "SELECT * FROM " + getTablePrefix() + "_product WHERE owner_id = ? ORDER BY id ASC";
    private static final String queryInsertProduct = "INSERT INTO " + getTablePrefix() + "_product (status, online, weight, price, name, description, inexpensive, professional, for_child, used, min_age, owner_id, insert_date, brand_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
    private static final String queryRemoveProduct = "DELETE FROM " + getTablePrefix() + "_product WHERE id = ?";
    private static final String queryRemoveProductImages = "DELETE FROM " + getTablePrefix() + "_product_images WHERE product_id = ?";
    private static final String queryinsertProductImage = "INSERT INTO " + getTablePrefix() + "_product_images (image, product_id) VALUES (?,?)";
    private static final long serialVersionUID = 1L;

    public static void editProduct(ProductBean productBean) throws SQLException {
        try (PreparedStatement prepareStatement = getConnection().prepareStatement(queryEditProduct)) {
            prepareStatement.setBoolean(1, productBean.isStatus());
            prepareStatement.setBoolean(2, productBean.isOnline());
            prepareStatement.setFloat(3, productBean.getWeight());
            prepareStatement.setFloat(4, productBean.getPrice());
            prepareStatement.setString(5, productBean.getName());
            prepareStatement.setString(6, productBean.getDescription());
            prepareStatement.setBoolean(7, productBean.isInexpensive());
            prepareStatement.setBoolean(8, productBean.isProfessional());
            prepareStatement.setBoolean(9, productBean.isForChild());
            prepareStatement.setBoolean(10, productBean.isUsed());
            prepareStatement.setInt(11, productBean.getMinAge());
            prepareStatement.setInt(12, productBean.getBrand().getID());
            prepareStatement.setInt(13, productBean.getID());
            prepareStatement.execute();
        }
        removeProductImages(productBean.getID());
        insertProductImages(productBean);
    }

    public static List<ProductBean> getOnlineProducts() throws SQLException {
        ArrayList<ProductBean> result = new ArrayList<>();
        try (Statement statement = getConnection().createStatement()) {
            try (ResultSet resultSet = statement.executeQuery(queryGetOnlineProducts)) {
                while (resultSet.next()) {
                    result.add(makeProduct(resultSet));
                }
            }
        }
        return result;
    }

    public static List<ProductBean> getProductsByOwner(int customerID) throws SQLException {
        ArrayList<ProductBean> result = new ArrayList<>();
        try (PreparedStatement preparedStatement = getConnection().prepareStatement(queryGetProductsByOwner)) {
            preparedStatement.setInt(1, customerID);
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                while (resultSet.next()) {
                    result.add(makeProduct(resultSet));
                }
            }
        }
        return result;
    }

    public static ProductBean getProduct(int productID) throws SQLException {
        ProductBean result = new ProductBean();
        try (PreparedStatement prepareStatement = getConnection().prepareStatement(queryGetProduct)) {
            prepareStatement.setInt(1, productID);
            try (ResultSet resultSet = prepareStatement.executeQuery()) {
                if (resultSet.next()) {
                    result = (makeProduct(resultSet));
                }
            }
        }
        return result;
    }

    public static List<String> getProductImages(int productID) throws SQLException {
        LinkedList<String> result = new LinkedList<>();
        try (PreparedStatement prepareStatement = getConnection().prepareStatement(queryGetProductImages)) {
            prepareStatement.setInt(1, productID);
            try (ResultSet resultSet = prepareStatement.executeQuery()) {
                while (resultSet.next()) {
                    result.add(resultSet.getString("image"));
                }
            }
        }
        return result;
    }

    public static List<ProductBean> getProducts(Map<String, Boolean> filters) throws SQLException {
        ArrayList<ProductBean> result = new ArrayList<>();
        String query = "SELECT * FROM " + getTablePrefix() + "_product ";
        if (filters.size() > 0) {
            query += "WHERE ";
            for (Iterator<Entry<String, Boolean>> it = filters.entrySet().iterator(); it.hasNext();) {
                Map.Entry<String, Boolean> entry = it.next();
                query = query.concat(entry.getKey().concat(" = ? "));
                if (it.hasNext()) {
                    query = query.concat("AND ");
                }
            }
            query += "ORDER BY id ASC";
        }
        try (PreparedStatement preparedStatement = getConnection().prepareStatement(query)) {
            int i = 0;
            for (Entry<String, Boolean> entry : filters.entrySet()) {
                preparedStatement.setBoolean(++i, entry.getValue());
            }
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                while (resultSet.next()) {
                    result.add(makeProduct(resultSet));
                }
            }
        }
        return result;
    }

    public static List<ProductBean> getProductsByBrand(int brandID) throws SQLException {
        ArrayList<ProductBean> result = new ArrayList<>();
        try (PreparedStatement preparedStatement = getConnection().prepareStatement(queryGetProductsByBrand)) {
            preparedStatement.setInt(1, brandID);
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                while (resultSet.next()) {
                    result.add(makeProduct(resultSet));
                }
            }
        }
        return result;
    }

    public static void insertProduct(ProductBean productBean) throws SQLException {
        try (PreparedStatement prepareStatement = getConnection().prepareStatement(queryInsertProduct, Statement.RETURN_GENERATED_KEYS)) {
            prepareStatement.setBoolean(1, productBean.isStatus());
            prepareStatement.setBoolean(2, productBean.isOnline());
            prepareStatement.setFloat(3, productBean.getWeight());
            prepareStatement.setFloat(4, productBean.getPrice());
            prepareStatement.setString(5, productBean.getName());
            prepareStatement.setString(6, productBean.getDescription());
            prepareStatement.setBoolean(7, productBean.isInexpensive());
            prepareStatement.setBoolean(8, productBean.isProfessional());
            prepareStatement.setBoolean(9, productBean.isForChild());
            prepareStatement.setBoolean(10, productBean.isUsed());
            if (productBean.isForChild()) {
                prepareStatement.setInt(11, productBean.getMinAge());
            } else {
                prepareStatement.setNull(11, java.sql.Types.INTEGER);
            }
            if (productBean.isUsed() && productBean.getOwner().getID() > 0) {
                prepareStatement.setInt(12, productBean.getOwner().getID());
            } else {
                prepareStatement.setNull(12, java.sql.Types.INTEGER);
            }
            prepareStatement.setDate(13, java.sql.Date.valueOf(productBean.getInsertDate()));
            prepareStatement.setInt(14, productBean.getBrand().getID());
            int affectedRows = prepareStatement.executeUpdate();

            if (affectedRows == 0) {
                throw new SQLException("Creating product failed, no rows affected.");
            }

            try (ResultSet generatedKeys = prepareStatement.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    productBean.setID(generatedKeys.getInt("id"));
                } else {
                    throw new SQLException("Creating product failed, no ID obtained.");
                }
            }
            insertProductImages(productBean);
        }
    }

    public static void removeProduct(int productID) throws SQLException {
        removeProductImages(productID);
        try (PreparedStatement prepareStatement = getConnection().prepareStatement(queryRemoveProduct)) {
            prepareStatement.setInt(1, productID);
            prepareStatement.execute();
        }
    }

    private static void insertProductImages(ProductBean productBean) throws SQLException {
        for (String image : productBean.getProductImages()) {

src/java/it/univr/musiclovers/model/beans/ProductBean.java
package it.univr.musiclovers.model.beans;

import it.univr.musiclovers.model.Model;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class ProductBean implements Serializable {

    private int ID;

    private BrandBean brand = new BrandBean();
    private String description;
    private boolean forChild;
    private boolean inexpensive;
    private String insertDate = Model.today();
    private int minAge;
    private String name;
    private boolean online;
    private float price;
    private List<String> productImage = new ArrayList<>();
    private boolean professional;
    private ProfessionalBean owner = new ProfessionalBean();
    private boolean status;
    private boolean used;
    private float weight;

    private static final long serialVersionUID = 1L;

    public BrandBean getBrand() {
        return brand;
    }

    public void setBrand(BrandBean brand) {
        this.brand = brand;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getID() {
        return ID;
    }

    public void setID(int ID) {
        this.ID = ID;
    }

    public String getInsertDate() {
        return insertDate;
    }

    public void setInsertDate(String insertDate) {
        this.insertDate = insertDate;
    }

    public int getMinAge() {
        return minAge;
    }

    public void setMinAge(int min_age) {
        this.minAge = min_age;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public float getPrice() {
        return price;
    }

    public void setPrice(float price) {
        this.price = price;
    }

    public void setProductImage(List<String> product_image) {
        this.productImage = new ArrayList<>(product_image);
    }

    public List<String> getProductImages() {
        return productImage;
    }

    public ProfessionalBean getOwner() {
        return owner;
    }

    public void setOwner(ProfessionalBean owner) {
        this.owner = owner;
    }

    public String getThumb() {
        if (productImage.isEmpty()) {
            return "img/image-not-found.png";
        } else {
            return productImage.get(0);
        }
    }

    public float getWeight() {
        return weight;
    }

    public void setWeight(float weight) {
        this.weight = weight;
    }

    public boolean isForChild() {
        return forChild;
    }

    public void setForChild(boolean forChild) {
        this.forChild = forChild;
    }

    public boolean isInexpensive() {
        return inexpensive;
    }

    public void setInexpensive(boolean inexpensive) {
        this.inexpensive = inexpensive;
    }

    public boolean isOnline() {
        return online;
    }

    public void setOnline(boolean online) {
        this.online = online;
    }

    public boolean isProfessional() {
        return professional;
    }

    public void setProfessional(boolean professional) {
        this.professional = professional;
    }

    public boolean isStatus() {
        return status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

    public boolean isUsed() {
        return used;
    }

    public void setUsed(boolean used) {
        this.used = used;
    }

}

src/java/it/univr/musiclovers/controller/BrandController.java
package it.univr.musiclovers.controller;

import it.univr.musiclovers.model.BrandModel;
import it.univr.musiclovers.model.ProductModel;
import it.univr.musiclovers.model.beans.BrandBean;
import it.univr.musiclovers.model.beans.ProductBean;
import java.io.*;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.ServletContext;
import javax.servlet.http.Part;

/**
 *
 * @author Marian Solomon
 */
@ManagedBean
@SessionScoped
public class BrandController extends ControllerModel {

    private transient Part file;
    private BrandBean selectedBrand;
    private static final long serialVersionUID = 1L;

    public String getBrand(int brandID) {
        return addParam(normalizeUrl("brand"), "brandID", String.valueOf(brandID));
    }

    public String getBrandInfo(int brandID) {
        return addParam(normalizeUrl("/brand"), "brandID", String.valueOf(brandID));
    }

    public List<BrandBean> getBrands() throws SQLException {
        return BrandModel.getBrands();
    }

    public Part getFile() {
        return file;
    }

    public void setFile(Part file) {
        this.file = file;
    }

    public List<ProductBean> getProducts() throws SQLException {
        return ProductModel.getProductsByBrand(selectedBrand.getID());
    }

    public BrandBean getSelectedBrand() {
        return selectedBrand;
    }

    public void setSelectedBrand(int brandId) throws SQLException {
        this.selectedBrand = BrandModel.getBrand(brandId);
    }

    public String processBrandForm() throws SQLException {
        if (selectedBrand.getID() > 0) {
            BrandModel.editBrand(selectedBrand);
        } else {
            BrandModel.insertBrand(selectedBrand);
        }
        return "index.xhtml";
    }

    public void processImage() {
        if (file != null) {
            try (InputStream inputStream = file.getInputStream()) {
                String pathWebBuild = ((ServletContext) FacesContext.getCurrentInstance().getExternalContext().getContext()).getRealPath("");
                String pathWebSrc = pathWebBuild + "/img/brands/";
                File outputFile = new File(pathWebSrc + File.separator + File.separator + getFilename(file));
                try (FileOutputStream outputStream = new FileOutputStream(outputFile)) {
                    byte[] buffer = new byte[4096];
                    int bytesRead = 0;
                    while (true) {
                        bytesRead = inputStream.read(buffer);
                        if (bytesRead > 0) {
                            outputStream.write(buffer, 0, bytesRead);
                        } else {
                            break;
                        }
                    }
                }
                selectedBrand.setLogo("img/brands/" + getFilename(file));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(ProductController.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(ProductController.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void removeBrand(int brandID) throws SQLException, ParseException {
        if (BrandModel.getBrandsByProduct(brandID).isEmpty()) {
            BrandModel.removeBrand(brandID);
        } else {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Errore", ":  impossibile eliminare un brand a cui vi sono ancora prodotti associati!"));
        }
    }

    public void removeLogo(String logo) throws SQLException {
        selectedBrand.setLogo("img/image-not-found.png");
    }

    private static String getFilename(Part part) {
        for (String cd : part.getHeader("content-disposition").split(";")) {
            if (cd.trim().startsWith("filename")) {
                String filename = cd.substring(cd.indexOf('=') + 1).trim().replace("\"", "");
                return filename.substring(filename.lastIndexOf('/') + 1).substring(filename.lastIndexOf('\\') + 1); // MSIE fix.
            }
        }
        return null;
    }

}

web/brand.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html" 
      xmlns:ui="http://java.sun.com/jsf/facelets" 
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core">
    <head>
        <link rel="stylesheet" href="css/bootstrap.css" />
        <link rel="stylesheet" href="css/bootstrap-theme.css" />
        <link rel="stylesheet" href="css/custom.css" />
        <title>IGNORED</title>
    </head>
    <body>
        <ui:composition template="templates/template.jsf">
            <f:metadata>
                <f:viewAction action="${brandController.setSelectedBrand(param.brandID)}"/>
            </f:metadata>
            <ui:define name="windowTitle">${brandController.selectedBrand.name}</ui:define>
            <ui:define name="content">
                <div class="page-header">
                    <h1><h:outputText value="${brandController.selectedBrand.name}"/></h1>
                </div>
                <div class="container">
                    <div class="row thumbnail">
                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                            <h:graphicImage value="${brandController.selectedBrand.logo}" class="img-responsive img-rounded margin-10-auto min-height-100"/>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 lead">
                            <div class="small margin-top-10"><h:outputText value="${brandController.selectedBrand.description}"/></div>
                            <div class="well-lg">
                                Sito web: <h:outputLink target="_blank" value="${brandController.selectedBrand.link}">${brandController.selectedBrand.link}</h:outputLink>
                            </div>
                        </div>
                    </div>
                    <h:panelGroup layout="block" rendered="${brandController.products.size() > 0}" class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 margin-top-10" >    
                            <div id="brandCarousel" class="carousel slide" data-ride="carousel">
                                <ol class="carousel-indicators">
                                    <ui:repeat value="${brandController.products}" var="product" varStatus="indice" rendered="${brandController.products.size() le 20}">
                                        <li data-target="#brandCarousel" data-slide-to="${indice}" class="${indice.first? 'active':''}"></li>
                                    </ui:repeat>
                                </ol>
                                <div class="carousel-inner" role="listbox">
                                    <ui:repeat value="${brandController.products}" var="product" varStatus="indice">
                                        <div class="item ${indice.first ? 'active':''} height-400">
                                            <h:graphicImage value="${product.thumb}" class="img-responsive"/>
                                            <div class="carousel-caption">
                                                <h3><h:link value="${product.name}" outcome="${productController.getProduct(product.ID)}"/></h3>
                                                <p>${product.description}</p>
                                            </div>
                                        </div>
                                    </ui:repeat>
                                </div>
                                <a class="left carousel-control text-danger" href="#brandCarousel" role="button" data-slide="prev">
                                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                    <span class="sr-only">Previous</span>
                                </a>
                                <a class="right carousel-control text-danger" href="#brandCarousel" role="button" data-slide="next">
                                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </div>
                        </div>
                    </h:panelGroup>
                </div>
            </ui:define>
        </ui:composition>
    </body>
</html>

web/dataLoad.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <head>
        <link rel="stylesheet" href="css/bootstrap.css" />
        <link rel="stylesheet" href="css/bootstrap-theme.css" />
        <link rel="stylesheet" href="css/custom.css" />
        <title>IGNORED</title>
    </head>
    <body>    
        <ui:composition template="templates/template.jsf">
            <ui:define name="windowTitle">Homepage</ui:define>
            <ui:define name="content">
                <div class="page-header">
                    <h1>Data Loader</h1>
                </div> 
                <h:form>
                    <h:commandButton value="Carica i dati" action="${loaderDataBean.loadData()}" class="btn btn-success"/>
                </h:form>
            </ui:define>
        </ui:composition>
    </body>
</html>

web/homepage.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:jsf="http://xmlns.jcp.org/jsf">
    <head>
        <link rel="stylesheet" href="css/bootstrap.css" />
        <link rel="stylesheet" href="css/bootstrap-theme.css" />
        <link rel="stylesheet" href="css/custom.css" />
        <title>IGNORED</title>       
    </head>    
    <body>
        <ui:composition template="templates/template.jsf">
            <ui:define name="windowTitle">Homepage</ui:define>
            <ui:define name="content">
                <div class="page-header">
                    <h1>Benvenuti su MusicLovers.com <small>| L'ultima frontiera del mercato nero!</small></h1>
                </div>
                <div class="jumbotron">
                    <p class="lead">MusicLoverS è il posto perfetto dove cercare i tuoi strumenti preferiti, <h:link outcome="about.xhtml">scopri chi siamo..</h:link></p>
                </div>
                <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12 text-justify">
                    <p class="lead">Filtra i prodotti</p>
                    <h:form class="margin-5">                            
                        <div class="checkbox">
                            <f:ajax execute="forChild" render="product-list" onevent="ajaxEvent">
                                <h:selectBooleanCheckbox value="${filterController.forChild}" id="forChild"/>
                                <h:outputLabel value="for child" for="forChild" class="unselectable"/>
                            </f:ajax>
                        </div>
                        <div class="checkbox">
                            <f:ajax execute="inexpensive" render="product-list" onevent="ajaxEvent">
                                <h:selectBooleanCheckbox value="${filterController.inexpensive}" id="inexpensive"/>
                                <h:outputLabel value="inexpensive" for="inexpensive" class="unselectable"/>                    
                            </f:ajax>
                        </div>
                        <div class="checkbox">
                            <f:ajax execute="professional" render="product-list" onevent="ajaxEvent">
                                <h:selectBooleanCheckbox value="${filterController.professional}" id="professional"/>
                                <h:outputLabel value="professional" for="professional" class="unselectable"/>
                            </f:ajax>
                        </div>
                        <div class="checkbox">
                            <f:ajax execute="used" render="product-list" onevent="ajaxEvent">
                                <h:selectBooleanCheckbox value="${filterController.used}" id="used"/>
                                <h:outputLabel value="used" for="used" class="unselectable"/>
                            </f:ajax>
                        </div>
                    </h:form>
                </div>
                <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
                    <div class="grid" jsf:id="product-list">
                        <h:panelGroup rendered="${empty filterController.onlineProducts}" id="products-empty">
                            <p class="lead text-danger">Nessuno strumento soddisfa i requisiti selezionati!</p>
                        </h:panelGroup>
                        <ui:repeat value="${filterController.onlineProducts}" var="product">
                            <div class="col-lg-3 col-md-3 col-sm-4 col-xs-6 grid-item">
                                <div class="thumbnail">
                                    <h:outputLink value="${productController.getProduct(product.ID)}">
                                        <h:graphicImage value="${product.thumb}" />
                                    </h:outputLink>
                                    <h:outputText class="bg-info badge price-bage" value="${product.price} €" >
                                        <f:convertNumber minFractionDigits="2" />
                                    </h:outputText>
                                    <b><h:link value="${product.name}" outcome="${productController.getProduct(product.ID)}"/></b><br/>
                                    <table class="table table-responsive table-striped table-bordered table-condensed"> 
                                        <tr><td>Economico:</td>
                                            <td>
                                                <h:outputFormat rendered="${product.inexpensive}"><span class="glyphicon glyphicon-ok text-success"/></h:outputFormat>
                                                <h:outputFormat rendered="${not product.inexpensive}"><span class="glyphicon glyphicon-remove text-danger"/></h:outputFormat>                              
                                            </td>
                                        </tr>
                                        <tr><td>Professional:</td>
                                            <td>
                                                <h:outputFormat rendered="${product.professional}"><span class="glyphicon glyphicon-ok text-success"/></h:outputFormat>
                                                <h:outputFormat rendered="${not product.professional}"><span class="glyphicon glyphicon-remove text-danger"/></h:outputFormat>                           
                                            </td>
                                        </tr>
                                        <tr><td>Usato:</td>
                                            <td>
                                                <h:outputFormat rendered="${product.used}"><span class="glyphicon glyphicon-ok text-success"/></h:outputFormat>
                                                <h:outputFormat rendered="${not product.used}"><span class="glyphicon glyphicon-remove text-danger"/></h:outputFormat>                                
                                            </td>
                                        </tr>
                                        <tr><td>Per bambini:</td>
                                            <td>
                                                <h:outputFormat rendered="${product.forChild}"><span class="glyphicon glyphicon-ok text-success"/></h:outputFormat>
                                                <h:outputFormat rendered="${not product.forChild}"><span class="glyphicon glyphicon-remove text-danger"/></h:outputFormat>                                
                                            </td>
                                        </tr>
                                        <h:outputFormat rendered="${product.minAge > 0}">
                                            <tr><td>Et&agrave; minima:</td><td><span class="badge"> ${product.minAge}</span></td></tr>
                                        </h:outputFormat>
                                    </table>
                                </div>
                            </div>
                        </ui:repeat>
                    </div>
                </div>
            </ui:define>
        </ui:composition>        
    </body>
</html>